// COMPLEXITY OF DATA STRUCTURES

// ARRAY


// TIME COMPLEXITY

// INSERTION AT BEG - O(N)
// INSERTION AT MIDDLE - O(N)
// INSERTION AT END - O(1)
// DELETION AT BEG - O(N)
// DELETION AT MIDDLE -O(N)
// DELETION AT END - 0(1)
// INIT - O(N)
// SET -O(1)
// GET -O(1)
// TRAVESING -0(N)


// SPACE COMPLEXITY

// INSERTION AT BEG - O(1)
// INSERTION AT MIDDLE - O(1)
// INSERTION AT END - O(1)
// DELETION AT BEG - O(1)
// DELETION AT MIDDLE - O(1)
// DELETION AT END - O(1)


// LINKED LIST

// TIME COMPLEXITY


// INSERTION AT BEG - O(1)
// INSERTION AT MIDDLE - O(N)  BEACAUSE OF TRAVESING THROUGH ALL NODES IT TAKES N TIMES.
// INSERTION AT END - O(1)
// DELETION AT BEG - O(1)
// DELETION AT MIDDLE - O(N)
// DELETION AT END - O(1)
// SEARCHING - 0(N)


// SPACE COMPLEXITY

// INSERTION AT BEG - O(1)
// INSERTION AT MIDDLE - O(1)
// INSERTION AT END - O(1)
// DELETION AT BEG - O(1)
// DELETION AT MIDDLE - O(1)
// DELETION AT END - O(1)

// HASH TABLE 

// TIME COMPLEXITY

// INSERTION -O(1)
// SEARCHING -O(1)
// DELETION -O(1)



